version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=glady
      - POSTGRES_DB=gladytt

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gladytt
      SPRING_DATASOURCE_USERNAME: glady
      SPRING_DATASOURCE_PASSWORD: S3cret
